nginx:
#  image: nginx
  build: .
#  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  command: [nginx-debug, '-g', 'daemon off;']
#  volumes:
#    - ./files/nginx.conf:/etc/nginx/nginx.conf:ro
  environment:
   - NGINX_HOST=foobar.com
   - NGINX_PORT=80
  ports:
    - 8000:80
  expose:
    - 8000
