# Data Containers

storage:
  image: busybox:latest
  volumes:
    - /tmp


# Service Containers

#rabbitmq:
#  image: rabbitmq:latest

elasticsearch:
  image: elasticsearch:latest

tokumx:
  build: ../tokumx
  environment:
    - TOKU_HUGE_PAGES_OK=1
  expose:
    - 27017
  ports:
    - 27017:27107


# Server Containers

web:
  build: .
  command: invoke server --host 0.0.0.0 --port 5000
  environment:
    - SOURCE_BRANCH=master
    - SOURCE_REPO=https://github.com/CenterForOpenScience/osf.io.git
  expose:
    - 5000
  ports:
    - 5000:5000
  links:
    - tokumx:tokumx
    - elasticsearch:elasticsearch
  #  - rabbitmq:rabbitmq
  volumes:
    - ./settings/local.py:/code/website/settings/local.py
  volumes_from:
    - storage

# apiserver:
#   build: .
#   # command: invoke apiserver --host 0.0.0.0 --port 8000
#   command: python manage.py runserver 0.0.0.0:8000
#   environment:
#     - SOURCE_BRANCH=master
#     - SOURCE_REPO=https://github.com/CenterForOpenScience/osf.io.git
#   expose:
#     - 8000
#   ports:
#     - 8000:8000
#   links:
#     - tokumx:tokumx
#     - elasticsearch:elasticsearch
#   #  - rabbitmq:rabbitmq
#   volumes:
#     - ./settings/local.py:/code/website/settings/local.py
#   volumes_from:
#     - storage

# sharejs:
#   build: .
#   command: invoke sharejs --host 0.0.0.0 --port 7007
#   environment:
#     - SOURCE_BRANCH=master
#     - SOURCE_REPO=https://github.com/CenterForOpenScience/osf.io.git
#     # - SHAREJS_SERVER_HOST=0.0.0.0
#     # - SHAREJS_SERVER_PORT=7007
#     - SHAREJS_CORS_ALLOW_ORIGIN=http://localhost:5000
#     - SHAREJS_DB_HOST=osf_tokumx_1
#     - SHAREJS_DB_PORT=27017
#     - SHAREJS_DB_NAME=sharejs
#     - SHAREJS_DEBUG=false
#   expose:
#     - 7007
#   ports:
#     - 7007:7007
#   links:
#     - tokumx:tokumx

# celery:
#   build: .
#   command: invoke celery
#   environment:
#     - SOURCE_BRANCH=master
#     - SOURCE_REPO=https://github.com/CenterForOpenScience/osf.io.git
#   links:
#     - database:database
#     - rabbitmq:rabbitmq
#   volumes_from:
#     - storage
