# Data Containers

storage:
  image: busybox:latest
  volumes:
    - /tmp
    # - /home/.cos
    # - /code
    - /home
    - /code/website/settings/local.py


# Service Containers

rabbitmq:
  image: rabbitmq:latest

database:
  build: ../tokumx
  environment:
    - TOKU_HUGE_PAGES_OK=1


# Server Containers

sharejs:
  build: .
  command: invoke sharejs
  environment:
    - SOURCE_BRANCH=master
    - SOURCE_REPO=https://github.com/CenterForOpenScience/osf.io.git
  links:
    - database:database
  volumes:
    - /home
    - /code
  volumes_from:
    - storage

# celery:
#   build: .
#   command: invoke celery
#   environment:
#     - SOURCE_BRANCH=master
#     - SOURCE_REPO=https://github.com/CenterForOpenScience/osf.io.git
#   links:
#     - database:database
#     - rabbitmq:rabbitmq
#   volumes_from:
#     - storage
#
# web:
#   build: .
#   command: invoke server
#   environment:
#     - SOURCE_BRANCH=develop
#     - SOURCE_REPO=https://github.com/CenterForOpenScience/osf.io.git
#   ports:
#     - 5000:5000
#   expose:
#     - 5000
#   links:
#     - database:database
#     - rabbitmq:rabbitmq
#   volumes_from:
#     - storage
